CONTEXT_LENGTH = 48
IMAGE_SIZE = 256
BATCH_SIZE = 64
START_TOKEN = "<START>"
END_TOKEN = "<END>"
PLACEHOLDER = "<PLACEHOLDER>"
CARRIAGE_RETURN = "<CARRIAGE_RETURN>"
TOKEN_TO_EXCLUDE = [PLACEHOLDER, CARRIAGE_RETURN]